Description: Lambda Example
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: live
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequestorg.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Timeout: 120
